// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LinkSignout struct {
	Username    string `json:"username"`
	Clinicid    string `json:"clinicid"`
	Signouttime string `json:"signouttime"`
	User        *User  `json:"user"`
}

type Login struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Attempt    int    `json:"attempt"`
	Signintime string `json:"signintime"`
}

type NewSignout struct {
	Username    string `json:"username"`
	Clinicid    string `json:"clinicid"`
	Signouttime string `json:"signouttime"`
}

type NewUser struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	Createtime      string `json:"createtime"`
	Clinicid        string `json:"clinicid"`
	Roleid          int    `json:"roleid"`
	Accountstatus   int    `json:"accountstatus"`
	Sessionlifetime int    `json:"sessionlifetime"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type ReturnSignin struct {
	Status          string `json:"Status"`
	Sessionid       string `json:"Sessionid"`
	Clinicid        string `json:"Clinicid"`
	Userid          string `json:"Userid"`
	Roleid          int    `json:"Roleid"`
	Accountstatus   int    `json:"Accountstatus"`
	Sessionlifetime int    `json:"Sessionlifetime"`
}

type User struct {
	Userid   string `json:"userid"`
	Username string `json:"username"`
}
